# Generated by Django 5.2.11 on 2026-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(default='published', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
