# Generated by Django 5.2.11 on 2026-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="map_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
