# Generated by Django 5.2.11 on 2026-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=20),
        ),
    ]
